import React, {useMemo, useState, useEffect} from 'react';
import { createRoot } from 'react-dom/client';
import { Search, Clock, Timer, Shuffle, Image, Dice5, Grid3X3, MessageCircle, BookOpen, Sparkles, Users, Play, ChevronRight, Home, RotateCcw, Trophy, Eye, HelpCircle, Check, X, Plus, Minus } from 'lucide-react';
import './styles.css';
import { games, bibleWhoQuestions, bibleNonsenseQuestions, bodyTalkCategories, bibleSceneTeams, missionCards } from './data/gameData.js';

const iconMap={Search,Clock,Timer,Shuffle,Image,Dice5,Grid3X3,MessageCircle,BookOpen,Sparkles,Users,Play,Grid:Grid3X3};
const categories=["전체","진행 도구","퀴즈","단체 게임","당번 정하기","성경추리","몸동작 게임","관찰력 게임","액션 게임","추첨","랜덤 도구","말씀 게임"];

function Header({setPage}){return <header className="topbar"><button className="brand" onClick={()=>setPage('home')}><Home size={18}/>움공플레이</button><div className="pill">UMGONG PLAY</div></header>}
function Card({game,setPage}){const Icon=iconMap[game.icon]||Sparkles;return <button className="game-card" onClick={()=>setPage(game.id)}><div className="card-head"><div className={'icon '+game.color}><Icon size={30}/></div><div className="card-title"><div><span>{game.category}</span><span>{game.level}</span></div><h3>{game.name}</h3><p>{game.tagline}</p></div><ChevronRight className="chev"/></div><p className="desc">{game.description}</p><div className="card-bottom"><small>말씀 연결: {game.verse}</small><strong>시작하기</strong></div></button>}
function HomePage({setPage}){const[query,setQuery]=useState('');const[cat,setCat]=useState('전체');const filtered=useMemo(()=>games.filter(g=>(cat==='전체'||g.category===cat)&&`${g.name} ${g.tagline} ${g.description} ${g.category}`.toLowerCase().includes(query.toLowerCase())),[query,cat]);return <><section className="hero"><div className="hero-main"><div className="badge"><Sparkles size={16}/>UMGONG PLAY Web App</div><h1>예배와 모임을 움직이는<br/><b>움공플레이</b></h1><p>움직이는교회의 공동체 놀이와 예배 활동을 한곳에 모은 진행 도구입니다. 카테고리, 설명, 시작 버튼을 크게 배치해 현장에서 바로 사용할 수 있게 만들었습니다.</p><div className="stats"><div><b>{games.length}</b><span>게임 도구</span></div><div><b>큰 버튼</b><span>모바일 친화</span></div><div><b>팀 점수</b><span>레크리에이션</span></div></div></div><div className="guide"><h2>오늘 진행 흐름</h2>{['모임 성격을 정합니다','게임을 고릅니다','점수판으로 진행합니다'].map((t,i)=><div className="step" key={t}><b>{i+1}</b><p><strong>{t}</strong><br/><span>{i===0?'어린이, 청소년, 장년 모임에 맞게 난이도를 고릅니다.':i===1?'검색과 카테고리 필터로 필요한 활동을 빠르게 찾습니다.':'정답, 패스, 점수 버튼으로 진행 흐름을 끊지 않습니다.'}</span></p></div>)}</div></section><section className="tools"><label><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="게임 이름, 상황, 키워드로 검색하세요"/></label><div className="tabs">{categories.map(c=><button className={cat===c?'on':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div></section><section className="list-head"><h2>게임 모음</h2><p>총 {filtered.length}개 표시</p></section><section className="grid">{filtered.map(g=><Card key={g.id} game={g} setPage={setPage}/>)}</section></>}
function ScoreBoard(){const[teams,setTeams]=useState([{name:'1팀',score:0},{name:'2팀',score:0}]);return <div className="score"><div className="score-title"><Trophy size={20}/><b>점수판</b><button onClick={()=>setTeams([...teams,{name:`${teams.length+1}팀`,score:0}])}><Plus size={16}/>팀 추가</button></div>{teams.map((t,i)=><div className="team" key={t.name}><span>{t.name}</span><button onClick={()=>setTeams(teams.map((x,idx)=>idx===i?{...x,score:Math.max(0,x.score-5)}:x))}><Minus size={16}/></button><b>{t.score}</b><button onClick={()=>setTeams(teams.map((x,idx)=>idx===i?{...x,score:x.score+10}:x))}><Plus size={16}/></button></div>)}</div>}
function QuizPage({title,items,type}){const[index,setIndex]=useState(0);const[show,setShow]=useState(false);const[hint,setHint]=useState(false);const q=items[index%items.length];function next(){setShow(false);setHint(false);setIndex(i=>i+1)}return <div className="game-layout"><div className="play-area"><div className="game-top"><span>{index+1} / {items.length}</span><button onClick={next}>다음 문제</button></div><h1>{title}</h1><div className="question-card"><div className="qtype">{q.category||type}</div><div className="question">{type==='who'?q.clues.join('  +  '):q.question}</div>{hint&&<p className="hint"><HelpCircle size={18}/>힌트: {q.hint}</p>}{show&&<div className="answer"><Check size={26}/>{q.answer}<small>{q.note}</small></div>}</div><div className="actions"><button onClick={()=>setHint(true)}><Eye size={18}/>힌트 보기</button><button className="primary" onClick={()=>setShow(true)}>정답 보기</button><button onClick={next}><RotateCcw size={18}/>넘기기</button></div></div><ScoreBoard/></div>}
function BodyTalkPage(){const[cat,setCat]=useState('영화');const[list,setList]=useState(bodyTalkCategories['영화']);const[i,setI]=useState(0);useEffect(()=>{setList(bodyTalkCategories[cat]);setI(0)},[cat]);return <div className="game-layout"><div className="play-area"><h1>몸으로 말해요</h1><div className="tabs big">{Object.keys(bodyTalkCategories).map(c=><button className={cat===c?'on':''} onClick={()=>setCat(c)}>{c}</button>)}</div><div className="question-card"><div className="qtype">{cat} {i+1}/{list.length}</div><div className="question huge">{list[i]}</div><p className="hint">말하지 않고 몸짓으로만 설명하세요. 패스는 진행자가 정합니다.</p></div><div className="actions"><button onClick={()=>setI(Math.max(0,i-1))}>이전</button><button className="primary" onClick={()=>setI((i+1)%list.length)}>다음</button></div></div><ScoreBoard/></div>}
function ScenePage(){const[team,setTeam]=useState('1팀');const[i,setI]=useState(0);const list=bibleSceneTeams[team];return <div className="game-layout"><div className="play-area"><h1>성경 장면 연기</h1><div className="tabs big">{Object.keys(bibleSceneTeams).map(t=><button className={team===t?'on':''} onClick={()=>{setTeam(t);setI(0)}}>{t}</button>)}</div><div className="question-card"><div className="qtype">{team} 문제 {i+1}/{list.length}</div><div className="question">{list[i]}</div><p className="hint">30초 준비 후, 말없이 장면을 표현합니다.</p></div><div className="actions"><button onClick={()=>setI(Math.max(0,i-1))}>이전</button><button className="primary" onClick={()=>setI((i+1)%list.length)}>다음</button></div></div><ScoreBoard/></div>}
function SpinWheel(){const[names,setNames]=useState('기도자\n찬양인도\n대표기도\n봉헌\n간식정리');const[result,setResult]=useState('');const arr=names.split('\n').map(x=>x.trim()).filter(Boolean);return <div className="solo"><h1>스핀 돌리기</h1><textarea value={names} onChange={e=>setNames(e.target.value)} /><button className="mega" onClick={()=>setResult(arr[Math.floor(Math.random()*arr.length)]||'입력 필요')}>돌리기</button>{result&&<div className="result">오늘의 선택: <b>{result}</b></div>}</div>}
function MissionBox(){const[i,setI]=useState(0);return <div className="solo"><h1>미션 박스</h1><div className="mission">{missionCards[i]}</div><button className="mega" onClick={()=>setI(Math.floor(Math.random()*missionCards.length))}>랜덤 뽑기</button></div>}
function TimerTool({kind}){const[sec,setSec]=useState(kind==='timer'?60:0);const[run,setRun]=useState(false);useEffect(()=>{if(!run)return;const id=setInterval(()=>setSec(s=>kind==='timer'?Math.max(0,s-1):s+1),1000);return()=>clearInterval(id)},[run,kind]);return <div className="solo"><h1>{kind==='timer'?'타이머':'스톱워치'}</h1><div className="clock">{String(Math.floor(sec/60)).padStart(2,'0')}:{String(sec%60).padStart(2,'0')}</div>{kind==='timer'&&<input type="number" value={sec} onChange={e=>setSec(Number(e.target.value)||0)}/>}<div className="actions center"><button className="primary" onClick={()=>setRun(!run)}>{run?'멈춤':'시작'}</button><button onClick={()=>{setRun(false);setSec(kind==='timer'?60:0)}}>초기화</button></div></div>}
function Placeholder({id}){const game=games.find(g=>g.id===id);return <div className="solo"><h1>{game?.name||'게임'}</h1><p className="large">이 게임은 홈 화면과 배포 구조에 포함되어 있습니다. 세부 게임 화면은 다음 버전에서 확장하면 됩니다.</p><div className="notice">기본 배포 후, 우선순위에 따라 사다리타기·빙고·병뚜껑 결승전 등을 하나씩 붙이면 안전합니다.</div></div>}
function App(){const[page,setPage]=useState('home');let content;if(page==='home')content=<HomePage setPage={setPage}/>;else if(page==='bible-emoji-guess')content=<QuizPage title="내가 누구게?" items={bibleWhoQuestions} type="who"/>;else if(page==='bible-nonsense-battle')content=<QuizPage title="성경 넌센스 배틀" items={bibleNonsenseQuestions} type="넌센스"/>;else if(page==='body-talk')content=<BodyTalkPage/>;else if(page==='bible-scene-acting')content=<ScenePage/>;else if(page==='spin-wheel'||page==='random-pick')content=<SpinWheel/>;else if(page==='mission-box')content=<MissionBox/>;else if(page==='timer')content=<TimerTool kind="timer"/>;else if(page==='stopwatch')content=<TimerTool kind="stopwatch"/>;else content=<Placeholder id={page}/>;return <main><div className="bg"></div><div className="wrap"><Header setPage={setPage}/>{content}</div></main>}
createRoot(document.getElementById('root')).render(<App/>);
