import React, {useMemo, useState, useEffect} from 'react';
import { createRoot } from 'react-dom/client';
import { Search, Clock, Timer, Shuffle, Image, Dice5, Grid3X3, MessageCircle, BookOpen, Sparkles, Users, Play, ChevronRight, Home, RotateCcw, Trophy, Eye, HelpCircle, Check, Plus, Minus, ArrowLeft, Flag } from 'lucide-react';
import './styles.css';
import { games, bibleWhoQuestions, bibleNonsenseQuestions, chosungQuestions, sentenceQuestions, bodyTalkCategories, bibleSceneTeams, missionCards, bingoWords, relayWords, overlapItems } from './data/gameData.js';

const iconMap={Search,Clock,Timer,Shuffle,Image,Dice5,Grid3X3,MessageCircle,BookOpen,Sparkles,Users,Play};
const categories=["전체","진행 도구","퀴즈","단체 게임","당번 정하기","성경추리","몸동작 게임","관찰력 게임","액션 게임","추첨","랜덤 도구","말씀 게임"];
const pick=(arr)=>arr[Math.floor(Math.random()*arr.length)];

function Header({setPage}){return <header className="topbar"><button className="brand" onClick={()=>setPage('home')}><Home size={18}/>움공플레이</button><div className="pill">UMGONG PLAY</div></header>}
function Back({setPage,title}){return <div className="subbar"><button onClick={()=>setPage('home')}><ArrowLeft size={18}/>홈으로</button><b>{title}</b></div>}
function Card({game,setPage}){const Icon=iconMap[game.icon]||Sparkles;return <button className="game-card" onClick={()=>setPage(game.id)}><div className="card-head"><div className={'icon '+game.color}><Icon size={30}/></div><div className="card-title"><div><span>{game.category}</span><span>{game.level}</span></div><h3>{game.name}</h3><p>{game.tagline}</p></div><ChevronRight className="chev"/></div><p className="desc">{game.description}</p><div className="card-bottom"><small>말씀 연결: {game.verse}</small><strong>시작하기</strong></div></button>}
function HomePage({setPage}){const[query,setQuery]=useState('');const[cat,setCat]=useState('전체');const filtered=useMemo(()=>games.filter(g=>(cat==='전체'||g.category===cat)&&`${g.name} ${g.tagline} ${g.description} ${g.category}`.toLowerCase().includes(query.toLowerCase())),[query,cat]);return <><section className="hero"><div className="hero-main"><div className="badge"><Sparkles size={16}/>UMGONG PLAY Web App</div><h1>예배와 모임을 움직이는<br/><b>움공플레이</b></h1><p>움직이는교회의 공동체 놀이와 예배 활동을 한곳에 모은 진행 도구입니다. 모든 카드의 시작하기 버튼이 실제 게임 화면으로 연결되도록 보강했습니다.</p><div className="stats"><div><b>{games.length}</b><span>게임 도구</span></div><div><b>즉시 실행</b><span>빈 화면 없음</span></div><div><b>팀 점수</b><span>현장 진행</span></div></div></div><div className="guide"><h2>오늘 진행 흐름</h2>{['모임 성격을 정합니다','게임을 고릅니다','점수판으로 진행합니다'].map((t,i)=><div className="step" key={t}><b>{i+1}</b><p><strong>{t}</strong><br/><span>{i===0?'어린이, 청소년, 장년 모임에 맞게 난이도를 고릅니다.':i===1?'검색과 카테고리 필터로 필요한 활동을 빠르게 찾습니다.':'정답, 패스, 점수 버튼으로 진행 흐름을 끊지 않습니다.'}</span></p></div>)}</div></section><section className="tools"><label><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="게임 이름, 상황, 키워드로 검색하세요"/></label><div className="tabs">{categories.map(c=><button className={cat===c?'on':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div></section><section className="list-head"><h2>게임 모음</h2><p>총 {filtered.length}개 표시</p></section><section className="grid">{filtered.map(g=><Card key={g.id} game={g} setPage={setPage}/>)}</section></>}
function ScoreBoard(){const[teams,setTeams]=useState([{name:'1팀',score:0},{name:'2팀',score:0}]);return <div className="score"><div className="score-title"><Trophy size={20}/><b>점수판</b><button onClick={()=>setTeams([...teams,{name:`${teams.length+1}팀`,score:0}])}><Plus size={16}/>팀 추가</button></div>{teams.map((t,i)=><div className="team" key={i}><span>{t.name}</span><button onClick={()=>setTeams(teams.map((x,idx)=>idx===i?{...x,score:Math.max(0,x.score-5)}:x))}><Minus size={16}/></button><b>{t.score}</b><button onClick={()=>setTeams(teams.map((x,idx)=>idx===i?{...x,score:x.score+10}:x))}><Plus size={16}/></button></div>)}</div>}
function QuizPage({setPage,title,items,type}){const[index,setIndex]=useState(0);const[show,setShow]=useState(false);const[hint,setHint]=useState(false);const q=items[index%items.length];function next(){setShow(false);setHint(false);setIndex(i=>i+1)}return <><Back setPage={setPage} title={title}/><div className="game-layout"><div className="play-area"><div className="game-top"><span>{index+1} / {items.length}</span><button onClick={next}>다음 문제</button></div><h1>{title}</h1><div className="question-card"><div className="qtype">{q.category||type}</div><div className="question">{type==='who'?q.clues.join('  +  '):q.question||q.q}</div>{hint&&<p className="hint"><HelpCircle size={18}/>힌트: {q.hint}</p>}{show&&<div className="answer"><Check size={26}/>{q.answer}<small>{q.note}</small></div>}</div><div className="actions"><button onClick={()=>setHint(true)}><Eye size={18}/>힌트 보기</button><button className="primary" onClick={()=>setShow(true)}>정답 보기</button><button onClick={next}><RotateCcw size={18}/>넘기기</button></div></div><ScoreBoard/></div></>}
function BodyTalkPage({setPage}){const[cat,setCat]=useState('영화');const[list,setList]=useState(bodyTalkCategories['영화']);const[i,setI]=useState(0);useEffect(()=>{setList(bodyTalkCategories[cat]);setI(0)},[cat]);return <><Back setPage={setPage} title="몸으로 말해요"/><div className="game-layout"><div className="play-area"><h1>몸으로 말해요</h1><div className="tabs big">{Object.keys(bodyTalkCategories).map(c=><button className={cat===c?'on':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><div className="question-card"><div className="qtype">{cat} {i+1}/{list.length}</div><div className="question huge">{list[i]}</div><p className="hint">말하지 않고 몸짓으로만 설명하세요. 패스는 진행자가 정합니다.</p></div><div className="actions"><button onClick={()=>setI(Math.max(0,i-1))}>이전</button><button className="primary" onClick={()=>setI((i+1)%list.length)}>다음</button></div></div><ScoreBoard/></div></>}
function ScenePage({setPage}){const[team,setTeam]=useState('1팀');const[i,setI]=useState(0);const list=bibleSceneTeams[team];return <><Back setPage={setPage} title="성경 장면 연기"/><div className="game-layout"><div className="play-area"><h1>성경 장면 연기</h1><div className="tabs big">{Object.keys(bibleSceneTeams).map(t=><button className={team===t?'on':''} onClick={()=>{setTeam(t);setI(0)}} key={t}>{t}</button>)}</div><div className="question-card"><div className="qtype">{team} 문제 {i+1}/{list.length}</div><div className="question">{list[i]}</div><p className="hint">30초 준비 후, 말없이 장면을 표현합니다.</p></div><div className="actions"><button onClick={()=>setI(Math.max(0,i-1))}>이전</button><button className="primary" onClick={()=>setI((i+1)%list.length)}>다음</button></div></div><ScoreBoard/></div></>}
function SpinWheel({setPage,title='스핀 돌리기'}){const[names,setNames]=useState('기도자\n찬양인도\n대표기도\n봉헌\n간식정리');const[result,setResult]=useState('');const arr=names.split('\n').map(x=>x.trim()).filter(Boolean);return <><Back setPage={setPage} title={title}/><div className="solo"><h1>{title}</h1><textarea value={names} onChange={e=>setNames(e.target.value)} /><button className="mega" onClick={()=>setResult(pick(arr)||'입력 필요')}>뽑기 / 돌리기</button>{result&&<div className="result">오늘의 선택: <b>{result}</b></div>}</div></>}
function MissionBox({setPage}){const[i,setI]=useState(0);return <><Back setPage={setPage} title="미션 박스"/><div className="solo"><h1>미션 박스</h1><div className="mission">{missionCards[i]}</div><button className="mega" onClick={()=>setI(Math.floor(Math.random()*missionCards.length))}>랜덤 뽑기</button></div></>}
function TimerTool({setPage,kind}){const[sec,setSec]=useState(kind==='timer'?60:0);const[run,setRun]=useState(false);useEffect(()=>{if(!run)return;const id=setInterval(()=>setSec(s=>kind==='timer'?Math.max(0,s-1):s+1),1000);return()=>clearInterval(id)},[run,kind]);return <><Back setPage={setPage} title={kind==='timer'?'타이머':'스톱워치'}/><div className="solo"><h1>{kind==='timer'?'타이머':'스톱워치'}</h1><div className="clock">{String(Math.floor(sec/60)).padStart(2,'0')}:{String(sec%60).padStart(2,'0')}</div>{kind==='timer'&&<input type="number" value={sec} onChange={e=>setSec(Number(e.target.value)||0)}/>}<div className="actions center"><button className="primary" onClick={()=>setRun(!run)}>{run?'멈춤':'시작'}</button><button onClick={()=>{setRun(false);setSec(kind==='timer'?60:0)}}>초기화</button></div></div></>}
function DiceYut({setPage}){const[dice,setDice]=useState(1);const[yut,setYut]=useState('도');const yuts=['도','개','걸','윷','모','빽도'];return <><Back setPage={setPage} title="주사위 / 윷놀이"/><div className="game-layout"><div className="play-area"><h1>주사위 / 윷놀이</h1><div className="two"><div className="mini"><div className="dice">{dice}</div><button className="mega" onClick={()=>setDice(1+Math.floor(Math.random()*6))}>주사위 굴리기</button></div><div className="mini"><div className="dice yut">{yut}</div><button className="mega" onClick={()=>setYut(pick(yuts))}>윷 던지기</button></div></div></div><ScoreBoard/></div></>}
function Bingo({setPage}){const[called,setCalled]=useState([]);const rest=bingoWords.filter(w=>!called.includes(w));return <><Back setPage={setPage} title="빙고 게임"/><div className="game-layout"><div className="play-area"><h1>빙고 게임</h1><button className="mega" onClick={()=>rest.length&&setCalled([...called,pick(rest)])}>단어 뽑기</button><div className="result">{called[called.length-1]||'단어를 뽑아주세요'}</div><div className="wordgrid">{called.map(w=><span key={w}>{w}</span>)}</div></div><ScoreBoard/></div></>}
function WordRelay({setPage}){const[word,setWord]=useState('사랑');const[history,setHistory]=useState(['사랑']);return <><Back setPage={setPage} title="단어 릴레이"/><div className="game-layout"><div className="play-area"><h1>단어 릴레이</h1><div className="question-card"><div className="qtype">현재 단어</div><div className="question huge">{word}</div><p className="hint">마지막 글자로 시작하는 단어를 말하세요.</p></div><div className="actions"><button className="primary" onClick={()=>{const n=pick(relayWords);setWord(n);setHistory([...history,n])}}>다음 제시어</button></div><div className="wordgrid">{history.map((w,i)=><span key={i}>{w}</span>)}</div></div><ScoreBoard/></div></>}
function SentenceMatch({setPage}){return <QuizPage setPage={setPage} title="문장 매칭" items={sentenceQuestions.map(x=>({question:x.front+' ...',answer:x.back,hint:x.hint,note:'앞 문장과 뒷 문장을 이어 맞히는 게임입니다.'}))} type="말씀"/>}
function Ladder({setPage}){const[names,setNames]=useState('임성원\n김집사\n박청년\n이선생');const[missions,setMissions]=useState('대표기도\n간식정리\n찬양시작\n오늘의 MVP');const[result,setResult]=useState([]);function run(){const a=names.split('\n').filter(Boolean),b=missions.split('\n').filter(Boolean).sort(()=>Math.random()-.5);setResult(a.map((n,i)=>`${n} → ${b[i%b.length]}`))}return <><Back setPage={setPage} title="사다리타기"/><div className="solo"><h1>사다리타기</h1><div className="two"><textarea value={names} onChange={e=>setNames(e.target.value)}/><textarea value={missions} onChange={e=>setMissions(e.target.value)}/></div><button className="mega" onClick={run}>사다리 결과 보기</button>{result.length>0&&<div className="result-list">{result.map(r=><p key={r}>{r}</p>)}</div>}</div></>}
function PhotoGuess({setPage}){const[step,setStep]=useState(1);const[show,setShow]=useState(false);return <><Back setPage={setPage} title="사진 맞추기"/><div className="game-layout"><div className="play-area"><h1>사진 맞추기</h1><div className={'photo step'+step}>🦁</div><p className="hint">단계가 올라갈수록 사진이 더 많이 보입니다.</p>{show&&<div className="answer"><Check/>정답: 사자</div>}<div className="actions"><button onClick={()=>setStep(Math.min(4,step+1))}>더 보기</button><button className="primary" onClick={()=>setShow(true)}>정답 보기</button><button onClick={()=>{setStep(1);setShow(false)}}>다시 시작</button></div></div><ScoreBoard/></div></>}
function OverlapGuess({setPage}){const[show,setShow]=useState(false);return <><Back setPage={setPage} title="겹친 그림 맞추기"/><div className="game-layout"><div className="play-area"><h1>겹친 그림 맞추기</h1><div className="overlap">{overlapItems.map((x,i)=><span style={{transform:`translate(${(i%5)*18}px,${Math.floor(i/5)*26}px) rotate(${i*11}deg)`}} key={x}>{['🍎','🚗','✝️','🐟','👑','📖','🐑','🕊️','📯','❤️'][i]}</span>)}</div>{show&&<div className="wordgrid">{overlapItems.map(w=><span key={w}>{w}</span>)}</div>}<div className="actions"><button className="primary" onClick={()=>setShow(true)}>정답 목록 보기</button></div></div><ScoreBoard/></div></>}
function BottleCap({setPage}){const[pos,setPos]=useState(0);function push(){setPos(Math.min(100,Math.max(0,pos+Math.floor(Math.random()*35)+5)))}return <><Back setPage={setPage} title="병뚜껑 결승전"/><div className="game-layout"><div className="play-area"><h1>병뚜껑 결승전</h1><div className="track"><Flag className="flag"/><div className="cap" style={{left:`${pos}%`}}>🟡</div></div><p className="hint">실제 병뚜껑 게임을 하면서 앱으로 위치와 점수를 기록할 수 있습니다. 결승선에 가장 가까운 팀 승리!</p><div className="actions"><button className="primary" onClick={push}>밀기</button><button onClick={()=>setPos(0)}>처음으로</button></div></div><ScoreBoard/></div></>}
function Chosung({setPage}){return <QuizPage setPage={setPage} title="초성 게임" items={chosungQuestions.map(x=>({question:x.q,answer:x.answer,hint:x.hint,note:'초성으로 성경 인물을 맞힙니다.'}))} type="초성"/>}
function App(){const[page,setPage]=useState('home');let content;if(page==='home')content=<HomePage setPage={setPage}/>;else if(page==='bible-emoji-guess')content=<QuizPage setPage={setPage} title="내가 누구게?" items={bibleWhoQuestions} type="who"/>;else if(page==='bible-nonsense-battle')content=<QuizPage setPage={setPage} title="성경 넌센스 배틀" items={bibleNonsenseQuestions} type="넌센스"/>;else if(page==='chosung')content=<Chosung setPage={setPage}/>;else if(page==='body-talk')content=<BodyTalkPage setPage={setPage}/>;else if(page==='bible-scene-acting')content=<ScenePage setPage={setPage}/>;else if(page==='spin-wheel')content=<SpinWheel setPage={setPage}/>;else if(page==='random-pick')content=<SpinWheel setPage={setPage} title="랜덤 뽑기"/>;else if(page==='mission-box')content=<MissionBox setPage={setPage}/>;else if(page==='timer')content=<TimerTool setPage={setPage} kind="timer"/>;else if(page==='stopwatch')content=<TimerTool setPage={setPage} kind="stopwatch"/>;else if(page==='dice')content=<DiceYut setPage={setPage}/>;else if(page==='bingo')content=<Bingo setPage={setPage}/>;else if(page==='word-relay')content=<WordRelay setPage={setPage}/>;else if(page==='sentence-match')content=<SentenceMatch setPage={setPage}/>;else if(page==='ladder')content=<Ladder setPage={setPage}/>;else if(page==='photo-guess')content=<PhotoGuess setPage={setPage}/>;else if(page==='overlap-guess')content=<OverlapGuess setPage={setPage}/>;else if(page==='bottlecap-race')content=<BottleCap setPage={setPage}/>;return <main><div className="bg"></div><div className="wrap"><Header setPage={setPage}/>{content}</div></main>}
createRoot(document.getElementById('root')).render(<App/>);
