import React, { useMemo, useRef, useState, useEffect } from 'react'
import { createRoot } from 'react-dom/client'
import { Home, Clock, Timer, Dice5, Grid3X3, MessageCircle, BookOpen, Shuffle, Image, Trophy, ArrowLeft, Play, RotateCcw, Eye, Lightbulb, Plus, Minus } from 'lucide-react'
import './styles.css'
import { bingoWords, chosungQuestions, photoQuestions, randomMissions, relayWords, sentenceQuestions, bibleNonsense } from './data/gameData'

const games = [
  { id:'stopwatch', name:'스톱워치', icon:Clock, desc:'목표 시간에 가장 가깝게 멈추기', tag:'진행 도구' },
  { id:'timer', name:'타이머', icon:Timer, desc:'미션 제한시간 카운트다운', tag:'진행 도구' },
  { id:'random-pick', name:'랜덤 뽑기', icon:Shuffle, desc:'당번·선물·미션을 공정하게 뽑기', tag:'추첨' },
  { id:'dice', name:'주사위 / 윷놀이', icon:Dice5, desc:'큰 화면 애니메이션 랜덤 도구', tag:'랜덤' },
  { id:'bingo', name:'빙고 게임', icon:Grid3X3, desc:'단어를 뽑고 빙고판에 체크', tag:'단체 게임' },
  { id:'word-relay', name:'단어 릴레이', icon:MessageCircle, desc:'제시어를 넘기며 이어가기', tag:'순발력' },
  { id:'sentence-match', name:'문장 매칭', icon:BookOpen, desc:'말씀 앞뒤를 맞히는 게임', tag:'말씀 게임' },
  { id:'chosung', name:'초성 게임', icon:MessageCircle, desc:'큰 초성·힌트·정답 공개', tag:'퀴즈쇼' },
  { id:'photo-guess', name:'사진 맞추기', icon:Image, desc:'단계별로 힌트가 열리는 관찰 게임', tag:'관찰력' },
  { id:'bible-nonsense', name:'성경 넌센스 배틀', icon:Trophy, desc:'웃으며 맞히는 성경 말장난 퀴즈', tag:'성경추리' },
]

function go(id){ window.history.pushState(null,'',`/${id}`); window.dispatchEvent(new Event('popstate')) }
function route(){ return window.location.pathname.split('/').filter(Boolean).pop() || 'home' }

function Shell({children,title}){return <main className="app"><nav className="top"><button className="back" onClick={()=>go('home')}><ArrowLeft/> 홈</button><strong className="brand">UMGONG PLAY</strong></nav>{title&&<h1 className="pageTitle">{title}</h1>}{children}</main>}
function ScoreBoard(){const [scores,setScores]=useState([0,0,0,0]);return <div className="score"><b>팀 점수판</b>{scores.map((s,i)=><div className="team" key={i}><span>{i+1}팀</span><button onClick={()=>setScores(v=>v.map((x,j)=>j===i?x-5:x))}><Minus size={16}/></button><strong>{s}</strong><button onClick={()=>setScores(v=>v.map((x,j)=>j===i?x+10:x))}><Plus size={16}/></button></div>)}</div>}
function HomePage(){return <Shell><section className="hero"><p className="eyebrow">움직이는교회 레크리에이션 웹앱</p><h1>예배와 모임을<br/>살아 움직이게 하는 <span>움공플레이</span></h1><p>원본 이음플레이처럼 진행자 화면에서 바로 쓸 수 있도록, 큰 글씨·큰 버튼·정답 공개·점수판 중심으로 다시 구성했습니다.</p></section><section className="grid">{games.map(g=>{const Icon=g.icon;return <button className="card" key={g.id} onClick={()=>go(g.id)}><div className="badge">{g.tag}</div><Icon className="cardIcon"/><h2>{g.name}</h2><p>{g.desc}</p><span className="start">시작하기</span></button>})}</section></Shell>}
function Stopwatch(){const [running,setRunning]=useState(false);const [elapsed,setElapsed]=useState(0);const last=useRef(0);useEffect(()=>{let id; if(running){last.current=Date.now(); id=setInterval(()=>{const now=Date.now();setElapsed(e=>e+now-last.current);last.current=now},33)} return()=>clearInterval(id)},[running]);return <Shell title="⏱️ 스톱워치"><div className="stage"><div className="bigTime">{(elapsed/1000).toFixed(2)}</div><p>목표 시간에 가장 가깝게 멈추는 팀이 승리합니다.</p><div className="actions"><button onClick={()=>setRunning(!running)}>{running?'멈추기':'시작'}</button><button onClick={()=>{setRunning(false);setElapsed(0)}}>초기화</button></div></div></Shell>}
function TimerGame(){const [sec,setSec]=useState(60);const [run,setRun]=useState(false);useEffect(()=>{if(!run||sec<=0)return;const id=setTimeout(()=>setSec(s=>s-1),1000);return()=>clearTimeout(id)},[run,sec]);return <Shell title="⏳ 타이머"><div className="stage"><div className="bigTime">{Math.floor(sec/60)}:{String(sec%60).padStart(2,'0')}</div><div className="actions"><button onClick={()=>setSec(30)}>30초</button><button onClick={()=>setSec(60)}>1분</button><button onClick={()=>setSec(180)}>3분</button><button onClick={()=>setRun(!run)}>{run?'정지':'시작'}</button></div></div></Shell>}
function Dice(){const [dice,setDice]=useState('🎲');const [yut,setYut]=useState('윷을 던져보세요');const roll=()=>{setDice(['⚀','⚁','⚂','⚃','⚄','⚅'][Math.floor(Math.random()*6)]);setYut(['도','개','걸','윷','모'][Math.floor(Math.random()*5)])};return <Shell title="🎲 주사위 / 윷놀이"><div className="stage"><div className="mega">{dice}</div><h2>{yut}</h2><button className="primary" onClick={roll}>굴리기</button></div></Shell>}
function RandomPick(){const [items,setItems]=useState('대표기도\n간식정리\n찬양인도\n오늘의 MVP');const [pick,setPick]=useState('');const arr=items.split('\n').map(x=>x.trim()).filter(Boolean);return <Shell title="🎁 랜덤 뽑기"><div className="two"><div className="panel"><textarea value={items} onChange={e=>setItems(e.target.value)} /><button className="primary" onClick={()=>setPick(arr[Math.floor(Math.random()*arr.length)]||'')}>뽑기</button></div><div className="result">{pick||'결과가 여기에 크게 나타납니다'}</div></div></Shell>}
function Bingo(){const [picked,setPicked]=useState([]);const next=()=>{const left=bingoWords.filter(w=>!picked.includes(w)); if(left.length) setPicked([...picked,left[Math.floor(Math.random()*left.length)]])};return <Shell title="🧩 빙고 게임"><div className="two"><div className="stage"><div className="result">{picked[picked.length-1]||'단어 뽑기'}</div><button className="primary" onClick={next}>다음 단어</button><button onClick={()=>setPicked([])}>초기화</button></div><div className="wordGrid">{bingoWords.map(w=><span className={picked.includes(w)?'done':''} key={w}>{w}</span>)}</div></div></Shell>}
function WordRelay(){const [idx,setIdx]=useState(0);return <Shell title="🔤 단어 릴레이"><div className="stage"><p>화면에 뜬 단어의 마지막 글자로 이어 말하세요.</p><div className="result">{relayWords[idx]}</div><button className="primary" onClick={()=>setIdx((idx+1)%relayWords.length)}>다음 제시어</button></div></Shell>}
function SentenceMatch(){const [i,setI]=useState(0);const [show,setShow]=useState(false);const q=sentenceQuestions[i];return <Shell title="📖 문장 매칭"><div className="two"><div className="stage"><p className="eyebrow">{q.ref}</p><div className="verse">“{q.front} …”</div>{show&&<div className="answer">{q.back}</div>}<div className="actions"><button onClick={()=>setShow(true)}>정답 보기</button><button onClick={()=>{setI((i+1)%sentenceQuestions.length);setShow(false)}}>다음 문제</button></div></div><ScoreBoard/></div></Shell>}
function QuizStage({title, data, renderQuestion}){const [i,setI]=useState(0);const [hint,setHint]=useState(0);const [answer,setAnswer]=useState(false);const q=data[i];return <Shell title={title}><div className="two"><div className="stage">{renderQuestion(q)}<div className="hintBox">{q.hints?.slice(0,hint).map((h,n)=><p key={h}>힌트 {n+1}. {h}</p>)}</div>{answer&&<div className="answer">정답: {q.answer || q.a}</div>}<div className="actions"><button onClick={()=>setHint(h=>Math.min((q.hints?.length||1),h+1))}><Lightbulb/> 힌트</button><button onClick={()=>setAnswer(true)}><Eye/> 정답</button><button onClick={()=>{setI((i+1)%data.length);setHint(0);setAnswer(false)}}><Play/> 다음</button></div></div><ScoreBoard/></div></Shell>}
function Chosung(){return <QuizStage title="🔠 초성 게임" data={chosungQuestions} renderQuestion={(q)=><><p className="eyebrow">{q.category}</p><div className="chosung">{q.prompt}</div></>}/>} 
function PhotoGuess(){return <QuizStage title="📷 사진 맞추기" data={photoQuestions} renderQuestion={(q)=><><p className="eyebrow">{q.title}</p><div className="photoReveal">{q.image}</div><p>단계별 힌트를 열어 무엇인지 맞혀보세요.</p></>}/>} 
function BibleNonsense(){return <QuizStage title="😂 성경 넌센스 배틀" data={bibleNonsense.map(x=>({...x,answer:x.a,hints:[x.hint]}))} renderQuestion={(q)=><div className="quizText">{q.q}</div>}/>} 
function App(){const [r,setR]=useState(route());useEffect(()=>{const f=()=>setR(route());window.addEventListener('popstate',f);return()=>window.removeEventListener('popstate',f)},[]);const pages={home:<HomePage/>, stopwatch:<Stopwatch/>, timer:<TimerGame/>, dice:<Dice/>, 'random-pick':<RandomPick/>, bingo:<Bingo/>, 'word-relay':<WordRelay/>, 'sentence-match':<SentenceMatch/>, chosung:<Chosung/>, 'photo-guess':<PhotoGuess/>, 'bible-nonsense':<BibleNonsense/>};return pages[r]||<HomePage/>}

createRoot(document.getElementById('root')).render(<App />)
